### PR TITLE
[MLGROUP-123]Login Page

### PR DESCRIPTION
**Pull request by SaraLopez03**
If the values ​​of the fields are incorrect, display a window informing that the data is incorrect

If the values ​​of the fields are correct, you should redirect to the route: www.prilicores.com/caja

Do not enable the enter button if any of the fields is empty

Show a spinner when enter is clicked until the BE responds

**all of the above acceptance criteria are met.**

### CODE REVIEW

**Comment by DanielMaru** [comment]
Love, congratulations. You are awesome. The description of the PR was awesome, you are doing so great! I'm sure when you start working you will be the best. I'm surprised, you now know a lot

**Comment by DanielMaru** [comment]
Another suggestion for the next PR (you can leave this one as is now): Please don't upload the package-log.json file and please don't upload files that are not mentioned on the user story for instance: NavBar component

But in general terms, everything looks sooo good

**Comment by SaraLopez03** [comment]
> Another suggestion for the next PR (you can leave this one as is now): Please don't upload the package-log.json file and please don't upload files that are not mentioned on the user story for instance: NavBar component
> 
> But in general terms, everything looks sooo good

**Comment by SaraLopez03** [comment]
my love, what beautiful words, I really don't deserve so much, thank you for loving me and teaching me so much day by day, if it weren't for you I wouldn't know everything I know now my love. heaven thanks for the comments I did not know about the package.js I thought that since it was the first time it was uploaded there.

**Pull request merged**
